name: Cypress Tests with Allure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  split-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate test chunks
        id: generate
        run: |
          mkdir -p test-chunks
          specs=$(find cypress/e2e/prod -name "*.cy.ts" | sort)
          echo "$specs" | awk '{print $0}' | split -l 2 - test-chunks/specs_

          CHUNKS_JSON="["

          i=0
          for f in test-chunks/specs_*; do
            specs_array=$(jq -R . < "$f" | jq -s .)
            chunk="{\"id\":\"chunk$i\",\"specs\":$specs_array}"
            if [ $i -gt 0 ]; then
              CHUNKS_JSON+=","
            fi
            CHUNKS_JSON+="$chunk"
            i=$((i+1))
          done

          CHUNKS_JSON+="]"
          echo "chunks=$CHUNKS_JSON" >> $GITHUB_OUTPUT

    outputs:
      chunks: ${{ steps.generate.outputs.chunks }}

  run-tests:
    needs: split-and-run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.split-and-run.outputs.chunks) }}

    name: Cypress - ${{ matrix.id }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Run Cypress specs
        run: |
          for spec in "${{ toJson(matrix.specs) }}" ; do
            CLEANED_SPEC=$(echo "$spec" | sed 's/[][]//g' | tr -d '"')
            echo "Running spec: $CLEANED_SPEC"
            npx cypress run --env version=prod,allure=true --spec "$CLEANED_SPEC"
          done

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.id }}
          path: allure-results

  merge-allure-reports:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download Allure Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Merge Allure Results
        run: |
          mkdir -p merged-allure-results
          find downloaded-artifacts -type d -name "allure-results-*" | while read dir; do
            cp -r "$dir"/* merged-allure-results/
          done

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate merged-allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-allure-report
          path: allure-report
