name: Cypress Tests with Allure

on:
  push:
    branches: [main]

jobs:
  cypress-job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results

  cypress-job-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-2.spec.cy.ts"
      - name: Upload Allure Results (Job 2)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-2
          path: allure-results

  cypress-job-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-3.spec.cy.ts"
      - name: Upload Allure Results (Job 3)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-3
          path: allure-results

  cypress-job-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results
  
  cypress-job-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results

  cypress-job-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results

  cypress-job-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results

  cypress-job-8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results


  cypress-job-9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results
  
  cypress-job-10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx cypress run --env version=prod allure=true --spec "cypress/e2e/prod/spec-1.spec.cy.ts"
      - name: Upload Allure Results (Job 1)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-1
          path: allure-results

  merge-allure:
    runs-on: ubuntu-latest
    needs:
      - cypress-job-1
      - cypress-job-2
      - cypress-job-3
      - cypress-job-4
      - cypress-job-5
      - cypress-job-6
      - cypress-job-7
      - cypress-job-8
      - cypress-job-9
      - cypress-job-10

    steps:
      - uses: actions/checkout@v4

      # Download all results
      - name: Download Allure Results
        run: |
          for i in {1..25}; do
            mkdir -p allure-results-merged/allure-results-$i
          done

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results-merged

      - name: Merge and Generate Allure Report
        run: |
          npm install -g allure-commandline
          mkdir -p allure-results
          for i in {1..25}; do
            cp -r allure-results-merged/allure-results-$i/* allure-results/ || true
          done
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
