name: Cypress Tests with Allure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec:
          - cypress/e2e/prod/BlogOne-test.spec.cy.ts
          - cypress/e2e/prod/BlogTwo-test.spec.cy.ts
          - cypress/e2e/prod/BlogThree-test.spec.cy.ts
          - cypress/e2e/prod/BlogFour-test.spec.cy.ts
          - cypress/e2e/prod/BlogFive-test.spec.cy.ts
          - cypress/e2e/prod/BlogSix-test.spec.cy.ts
          - cypress/e2e/prod/BlogSeven-test.spec.cy.ts
          - cypress/e2e/prod/BlogEight-test.spec.cy.ts
          - cypress/e2e/prod/BlogNine-test.spec.cy.ts
          - cypress/e2e/prod/BlogTen-test.spec.cy.ts


    name: Cypress Test - ${{ matrix.spec }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Run Cypress Test
        run: |
          npx cypress run --env version=prod,allure=true --spec "${{ matrix.spec }}"

      - name: Sanitize spec name for artifact
        id: sanitize
        run: |
          SAFE_NAME=$(echo "${{ matrix.spec }}" | tr '/.' '--')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ steps.sanitize.outputs.safe_name }}
          path: allure-results

  merge-allure-reports:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Download Allure Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Combine Allure Results
        run: |
          mkdir -p merged-allure-results
          find downloaded-artifacts -type d -name "allure-results-*" | while read dir; do
            cp -r "$dir"/* merged-allure-results/
          done

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate merged-allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-allure-report
          path: allure-report
