name: Cypress Tests with Allure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec:
          - cypress/e2e/prod/allBlogPage-test.spec.cy.ts
          - cypress/e2e/prod/homePage-test.spec.cy.ts

    name: Cypress Test - ${{ matrix.spec }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Run Cypress Test
        run: |
          npx cypress run --env version=prod,allure=true --spec "${{ matrix.spec }}"

      - name: Sanitize spec name for artifact
        id: sanitize
        run: |
          SAFE_NAME=$(echo "${{ matrix.spec }}" | tr '/.' '--')
          echo "safe_name=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ steps.sanitize.outputs.safe_name }}
          path: allure-results
